#!/bin/bash

# Install by:
# $ curl -o pst https://bin.wantguns.dev/client && chmod +x pst
#
# Usage:
# $ pst somefile.txt
# $ cat someimage.png | pst

# Change the url accordingly
URL="https://bin.nora.codes"

FILEPATH="$1"
FILENAME=$(basename -- "$FILEPATH")
EXTENSION="${FILENAME##*.}"

RESPONSE=$(curl --data-binary @${FILEPATH:-/dev/stdin} --url $URL)
PASTELINK="$URL$RESPONSE"

[ -z "$EXTENSION" ] && \
    echo "$PASTELINK" || \
    echo "$PASTELINK.$EXTENSION"
